<a href="https://colab.research.google.com/github/andrewc998/skills-copilot-codespaces-vscode/blob/main/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning in Pandas

### ETL

ETL stands for Extract, Transform, and Load. It’s a process used in data management to move data from various sources into a centralized data place for analysis and reporting. Here's a breakdown of each step:

    Extract: This is the process of gathering raw data from various sources such as databases, flat files, APIs, or web scraping. The goal is to extract data in its raw form, without changing or processing it.

    Transform: Once the data is extracted, it often needs to be cleaned, formatted, or aggregated. This step might include filtering out unwanted data, correcting errors, converting data types, merging different data sources, or performing calculations to prepare the data for analysis.

    Load: After transforming the data, it’s loaded into the target destination, which could be a database, data warehouse, or data lake. This is where it’s stored in a structured format that can be queried and analyzed.

In [7]:
# imports
import pandas as pd
import numpy as np

In [8]:
#DATA CLEANING
#involves checking duplicates
# check correct data, correct data types
# check missing values
# check outliers

In [9]:
# IN DEALING WITH DATA CLEANING
# remove - drop values esp if duplicates
# replace - impute manually (check if data is numeric or categorical; if numeric replace with mean or mode)

### Data Loading

In [6]:
# data loading
df_yelp = pd.read_csv("/content/Yelp_Reviews.csv",index_col=0)
df_yelp.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg

In [10]:
df_yelp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2610 entries, 1 to 4206
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   business_id  2610 non-null   object
 1   cool         2610 non-null   int64
 2   date         2610 non-null   object
 3   funny        2610 non-null   int64
 4   review_id    2610 non-null   object
 5   stars        2610 non-null   int64
 6   text         2610 non-null   object
 7   useful       2610 non-null   int64
 8   user_id      2610 non-null   object
dtypes: int64(4), object(5)
memory usage: 268.4+ KB

### Lambda Functions

Lambda functions are often a convenient way to write throw-away functions on the fly. If you need to write a more complicated function you may still need to use the more formal def method, but lambda functions provide a quick and concise way to write function

In [11]:
def splitter(text):
    return len(text.split())

In [12]:
# default function example
df_yelp["text"].apply(splitter)

1        58
2        30
4        30
5        82
10       32
       ...
689      61
4874     43
564      79
3458    185
4206     42
Name: text, Length: 2610, dtype: int64

In [13]:
# an example of a lambda function

# lambda x,y,z : x+y+z

df_yelp["text"].apply(lambda text: len(text.split()))

1        58
2        30
4        30
5        82
10       32
       ...
689      61
4874     43
564      79
3458    185
4206     42
Name: text, Length: 2610, dtype: int64

In [14]:
df_yelp["review_length"] = df_yelp["text"].apply(lambda text: len(text.split()))
df_yelp.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review_length
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32

### Lambda functions with conditionals

In [15]:
def sentiment(rating):
    if rating > 3:
        return "positive"
    else:
        return "Negative"

In [16]:
df_yelp["stars"].apply(sentiment).value_counts()

stars
positive    1745
Negative     865
Name: count, dtype: int64

In [17]:
# conditionals simple example

df_yelp["Sentiment"] = df_yelp["stars"].apply(lambda rating: "Positive"
                                              if rating > 3
                                              else "Negative")

In [18]:
df_yelp.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review_length,Sentiment
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58,Positive
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30,Negative
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30,Positive
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82,Negative
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32,Positive

In [19]:
def sentiment2(rating):
    if rating >=4:
        return "positive"
    elif rating >= 3 :
        return "Neutral"
    else:
        return "Negative"

In [20]:
df_yelp["stars"].apply(sentiment2)

1       positive
2       Negative
4       positive
5       Negative
10      positive
          ...
689     positive
4874    positive
564     positive
3458    Negative
4206    Negative
Name: stars, Length: 2610, dtype: object

In [52]:
# conditionals if else
df_yelp["stars"].apply(lambda rating: "positive"
                       if rating >=4 else "Neutral"
                        if rating >= 3 else "Negative").value_counts()

stars
positive    1524
Negative     564
Neutral      189
Name: count, dtype: int64

### Todo

In [22]:
# repeat the conditional example using Normal functions
def sentiment(rating):
    if rating > 3:
        return "positive"
    else:
        return "Negative"

df_yelp["Sentiment_normal_function"] = df_yelp["stars"].apply(sentiment)

In [23]:
# repeat the Conditional if else example using Normal functions
def sentiment2(rating):
    if rating >=4:
        return "positive"
    elif rating >= 3 :
        return "Neutral"
    else:
        return "Negative"

### Transformations

In [24]:
# Todo
# Example Tranforming date column  into years and reassign it to a [Review_year] column

df_yelp['Review_year'] = pd.to_datetime(df_yelp['date']).dt.year
df_yelp.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review_length,Sentiment,Sentiment_normal_function,Review_year
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,58,Positive,positive,2012
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,30,Negative,Negative,2014
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,30,Positive,positive,2014
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,82,Negative,Negative,2011
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,32,Positive,positive,2016

## Data Cleaning in pandas

### Dealing with duplicates

Dealing with duplicated values in data involves identifying and handling redundant entries that may distort analysis or lead to incorrect conclusions.

In [25]:
# check for duplicated values
df_yelp.duplicated().value_counts()

False    2277
True      333
Name: count, dtype: int64

In [26]:
# View duplicates
df_yelp[df_yelp.duplicated()].head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,review_length,Sentiment,Sentiment_normal_function,Review_year
4252,fIuquIgWrkNEM5yvYSHPgw,2,2014-08-05,0,X4glBKsOvs6fgjHNJ0IUjw,5,What a compassionate and thorough professional...,3,xDjaGtx-TZUDdUxRKJnKCA,72,Positive,positive,2014
3028,_JD_U3pZDynB6l8swzVlQA,0,2017-12-17,0,iuVHqEglBCmL1lAbw8B2Ow,5,Had to switch barbers because I moved and the ...,0,WBKGxL53Tcq2_CkPavBYQA,93,Positive,positive,2017
3046,yQUXMWSA8H7wvkLa4iCD8g,0,2014-08-28,0,KmKCR_cHmAYA12Uy3XPHCA,2,Rude waitress and slow service. No offers for ...,1,KeYB7tU5F5PFb7X1QoWJ6Q,78,Negative,Negative,2014
2322,1lLJDy73uBp_I2LJ0B0Fkw,1,2011-09-09,0,03dNKEDriDeZ8poYbiNyxQ,5,Was here for a party last weekend and had a bl...,0,ftLmo96CeyaNcVqHleDSHw,27,Positive,positive,2011
794,XXW_OFaYQkkGOGniujZFHg,0,2013-12-04,0,XxsMdJl8OTgeq5iEhp4JLQ,5,this is for the fireside lounge.\r\ngreat plac...,1,D1_nrBr4dOrs7M82OaBRwQ,37,Positive,positive,2013

In [27]:
# removing  duplicated values
df_yelp = df_yelp.drop_duplicates()

In [28]:
# verify that they have been removed

df_yelp.duplicated().value_counts()

False    2277
Name: count, dtype: int64

## Data Loading

In [29]:
# data loading for titanic dataset

df_titanic = pd.read_csv("/content/titanic.csv")
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S

In [30]:
# info
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1391 entries, 0 to 1390
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1391 non-null   float64
 1   Survived     1391 non-null   float64
 2   Pclass       1391 non-null   object
 3   Name         1391 non-null   object
 4   Sex          1391 non-null   object
 5   Age          1209 non-null   float64
 6   SibSp        1391 non-null   float64
 7   Parch        1391 non-null   float64
 8   Ticket       1391 non-null   object
 9   Fare         1391 non-null   float64
 10  Cabin        602 non-null    object
 11  Embarked     1289 non-null   object
dtypes: float64(6), object(6)
memory usage: 130.5+ KB

### Dealing with missing values

#### Detecting Null Values

In [31]:
# detecting null  values

df_titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          789
Embarked       102
dtype: int64

## Strategies for dealing with missing data

Detecting missing values isn't enough -- we need to deal with them in order to move forward. We have three options for dealing with missing values -- removing them from the dataset, keeping them, or replacing them with another value

In [32]:
#DATA CLEANING
#involves checking duplicates
# check correct data, correct data types
# check missing values
# check outliers

In [33]:
# IN DEALING WITH DATA CLEANING
# remove - drop values esp if duplicates
# replace - impute manually (check if data is numeric or categorical; if numeric replace with mean, median, max, mode or 0)
# for categorical data check the mode first and fill in missing values
#you can also drop them after checking percentage of missing values

In [34]:
# .isna() - checks for missing values
# .duplicated() - checks for duplicated values
# .fillna() - to fill in missing values

### Removing

The easiest way to deal with missing values is to drop the offending rows and/or columns. The downside to this is that we lose data in the process. This is a valid strategy on very large datasets -- however, on smaller datasets, throwing away data may be unacceptable

## Droping columns

In [35]:
# Dropping inplace
# df_titanic.drop("Cabin",axis=1,inplace=True)
# df_titanic.info()

In [36]:
# dropping and reasign
df_titanic = df_titanic.drop("Cabin",axis=1)

In [37]:
df_titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked       102
dtype: int64

### Replacing Missing values (imputing)

**Continuous data**

For continuous data, the best solution is to replace the missing values with the median value for that column. The median value is a good choice because it is least likely to influence the distribution of the dataset overall. If the dataset is symmetric, then the mean and the median will be the same value. If the dataset is not symmetric, then the mean is more likely to be skewed by outlier values, so the median is a better choice.

In [38]:
# recheck  for missing values
df_titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            182
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked       102
dtype: int64

In [53]:
age_median = df_titanic["Age"].median()
age_median

27.0

In [64]:
# example 1
df_titanic["Age"] = df_titanic["Age"].fillna(age_median)

In [65]:
# replacing with reassignment
df_titanic["Age"] = df_titanic["Age"].fillna(df_titanic["Age"].median())

In [66]:
# recheck  for missing values
df_titanic.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [58]:
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,S

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['PassengerId'].plot(kind='hist', bins=20, title='PassengerId')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Survived'].plot(kind='hist', bins=20, title='Survived')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Pclass').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('Sex').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_7.groupby('Ticket').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='index', y='PassengerId', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='PassengerId', y='Survived', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10.plot(kind='scatter', x='Survived', y='Age', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_11.plot(kind='scatter', x='Age', y='SibSp', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Survived']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Pclass')):
  _plot_series(series, series_name, i)
  fig.legend(title='Pclass', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Survived')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Survived']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Name')):
  _plot_series(series, series_name, i)
  fig.legend(title='Name', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Survived')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Survived']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_14.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Sex')):
  _plot_series(series, series_name, i)
  fig.legend(title='Sex', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Survived')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['Survived']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_15.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Ticket')):
  _plot_series(series, series_name, i)
  fig.legend(title='Ticket', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('Survived')

from matplotlib import pyplot as plt
_df_16['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['PassengerId'].plot(kind='line', figsize=(8, 4), title='PassengerId')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18['Survived'].plot(kind='line', figsize=(8, 4), title='Survived')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_19['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Name'].value_counts()
    for x_label, grp in _df_20.groupby('Pclass')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Pclass')
_ = plt.ylabel('Name')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Sex'].value_counts()
    for x_label, grp in _df_21.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('Sex')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Ticket'].value_counts()
    for x_label, grp in _df_22.groupby('Sex')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Sex')
_ = plt.ylabel('Ticket')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Embarked'].value_counts()
    for x_label, grp in _df_23.groupby('Ticket')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Ticket')
_ = plt.ylabel('Embarked')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_24['Pclass'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_24, x='index', y='Pclass', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_25['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_25, x='index', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_26['Sex'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_26, x='index', y='Sex', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_27['Ticket'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_27, x='index', y='Ticket', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

**Categorical data**

With categorical data, this is harder, since we don't have summary statistics to lean on such as the median or the mean. In this case, if one categorical value is much more common than others, it is a valid strategy to replace missing values with this common value. However, make sure to examine your data first. If all the categorical values are equally common, picking one to replace all the missing values may do more harm than good by skewing the distribution and introducing some false signal into your dataset

In [59]:
# recheck for missing values
df_titanic.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [69]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1391 entries, 0 to 1390
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1391 non-null   float64
 1   Survived     1391 non-null   float64
 2   Pclass       1391 non-null   object
 3   Name         1391 non-null   object
 4   Sex          1391 non-null   object
 5   Age          1391 non-null   float64
 6   SibSp        1391 non-null   float64
 7   Parch        1391 non-null   float64
 8   Ticket       1391 non-null   object
 9   Fare         1391 non-null   float64
 10  Embarked     1391 non-null   object
dtypes: float64(6), object(5)
memory usage: 119.7+ KB

In [68]:
print(df_titanic['Embarked'].isnull())

0       False
1       False
2       False
3       False
4       False
        ...
1386    False
1387    False
1388    False
1389    False
1390    False
Name: Embarked, Length: 1391, dtype: bool

In [60]:
# most common value
df_titanic["Embarked"].value_counts()

Embarked
S    932
C    285
Q    174
Name: count, dtype: int64

In [45]:
embarked_mode  = df_titanic["Embarked"].mode()
embarked_mode

0    S
Name: Embarked, dtype: object

In [46]:
# filling with a custom value
# df_titanic["Embarked"] = df_titanic["Embarked"].fillna("M")

In [70]:
# replacing with mode
df_titanic["Embarked"] = df_titanic["Embarked"].fillna(embarked_mode[0])

In [71]:
# recheck for missing values
df_titanic.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [49]:
df_titanic["Embarked"].value_counts()

Embarked
S    932
C    285
Q    174
Name: count, dtype: int64

In [50]:
# DATA ANALYSIS AND VIZUALISATION
# involves EDA
# are of 3 types - univariate, bivariate, multivariate
# groupby() in pd used to analyse and aggregate`f

In [51]:
# split - divides data in groups based on multiple columns
# apply - aggregates functions, mean, sum, count
# combine -  results combined into new data frame

# EG IN TITANIC DATASET : groupby() method to group the data by 'Sex' and 'Survived' columns.
# Then, it counts the occurrences of 'Survived' within each group using the count() method to produce a summary.