In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Lambda Functions - Lab

## Introduction

In this lab, you'll get some hands-on practice creating and using lambda functions.

## Objectives

In this lab you will:

* Create lambda functions to use as arguments of other functions   
* Use the `.map()` or `.apply()` method to apply a function to a pandas series or DataFrame

## Lambda Functions

In [5]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Yelp_Reviews.csv', index_col=0)
df.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g

## Simple arithmetic

Use a lambda function to create a new column called `'stars_squared'` by squaring the stars column.

In [6]:
# Your code
df['stars_squared'] = df['stars'].apply(lambda x: x**2)
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25

## Dates
Select the month from the date string using a lambda function.

In [9]:
# Your code here
df['month'] = df['date'].apply(lambda x : x.split('-')[1])
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,10
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,09
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,02
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,06

## What is the average number of words for a yelp review?
Do this with a single line of code.

In [10]:
df['text'].str.split().apply(lambda x : len(x)).mean()

77.06551724137931

## Create a new column for the number of words in the review

In [13]:
df['word_count'] = df['text'].str.split().apply(lambda x : len(x))
df.head(1)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month,word_count
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11,58

## Rewrite the following as a lambda function

Create a new column `'Review_Length'` by applying this lambda function to the `'Review_num_words'` column.

In [14]:
# Rewrite the following function as a lambda function
def rewrite_as_lambda(value):
    if len(value) < 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
# Hint: nest your if, else conditionals

df['Review_length'] = df['word_count'].apply(lambda a: 'Short' if a < 50 else ('Medium' if a < 80 else 'Long'))
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month,word_count,Review_length
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11,58,Medium
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,10,30,Short
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,09,30,Short
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,02,82,Long
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,06,32,Short

## Level Up: Dates Advanced
<img src="https://github.com/learn-co-curriculum/dsc-lambda-functions-lab/blob/master/images/world_map.png?raw=1" width="600">  

Print the first five rows of the `'date'` column.

In [15]:
df['date'].head()

1     2012-11-13
2     2014-10-23
4     2014-09-05
5     2011-02-25
10    2016-06-15
Name: date, dtype: object

Overwrite the `'date'` column by reordering the month and day from `YYYY-MM-DD` to `DD-MM-YYYY`. Try to do this using a lambda function.

In [16]:
df['date'] = df['date'].apply(lambda a: '-'.join([a.split('-')[2], a.split('-')[1], a.split('-')[0]]))
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month,word_count,Review_length
1,pomGBqfbxcqPv14c3XH-ZQ,0,13-11-2012,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11,58,Medium
2,jtQARsP6P-LbkyjbO1qNGg,1,23-10-2014,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,10,30,Short
4,Ums3gaP2qM3W1XcA5r6SsQ,0,05-09-2014,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,09,30,Short
5,vgfcTvK81oD4r50NMjU2Ag,0,25-02-2011,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,02,82,Long
10,yFumR3CWzpfvTH2FCthvVw,0,15-06-2016,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,06,32,Short

In [18]:
df['date'] = df['date'].apply(lambda x: '-'.join(x.split('-')[::-1]))
df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month,word_count,Review_length
1,pomGBqfbxcqPv14c3XH-ZQ,0,13-11-2012,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11,58,Medium
2,jtQARsP6P-LbkyjbO1qNGg,1,23-10-2014,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,10,30,Short
4,Ums3gaP2qM3W1XcA5r6SsQ,0,05-09-2014,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,09,30,Short
5,vgfcTvK81oD4r50NMjU2Ag,0,25-02-2011,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,02,82,Long
10,yFumR3CWzpfvTH2FCthvVw,0,15-06-2016,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,06,32,Short

## Summary

Hopefully, you're getting the hang of lambda functions now! It's important not to overuse them - it will often make more sense to define a function so that it's reusable elsewhere. But whenever you need to quickly apply some simple processing to a collection of data you have a new technique that will help you to do just that. It'll also be useful if you're reading someone else's code that happens to use lambdas.