<a href="https://colab.research.google.com/github/andrewc998/skills-copilot-codespaces-vscode/blob/main/Titanic_pivot_tables_14th_Mrch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df_titanic = pd.read_csv('/content/drive/MyDrive/titanic.csv')
df_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S

In [17]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [18]:
#remove duplicates
df_titanic = df_titanic.drop_duplicates()

In [19]:
#remove null values
df_titanic = df_titanic.dropna()

In [20]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 476 entries, 1 to 1390
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  476 non-null    float64
 1   Survived     476 non-null    float64
 2   Pclass       476 non-null    object
 3   Name         476 non-null    object
 4   Sex          476 non-null    object
 5   Age          476 non-null    float64
 6   SibSp        476 non-null    float64
 7   Parch        476 non-null    float64
 8   Ticket       476 non-null    object
 9   Fare         476 non-null    float64
 10  Cabin        476 non-null    object
 11  Embarked     476 non-null    object
dtypes: float64(6), object(6)
memory usage: 48.3+ KB

In [21]:
#group by 'sex' and find average fare for each sex
df_titanic.groupby('Sex')['Fare'].describe()

,count,mean,std,min,25%,50%,75%,max
Sex,,,,,,,,
female,226.0,57.132966,61.606565,4.0125,10.500,29.8500,79.450000,263.0000
male,250.0,52.133817,70.099645,0.0000,12.875,30.0354,65.789575,512.3292

In [22]:
# shows that male were many
df_titanic['Sex'].value_counts()

Sex
male      250
female    226
Name: count, dtype: int64

In [23]:
#groupby sex and pclass to get aggregate
#shows that despite females having highest mean fare, male were many
# might be issue of unclean data, zeros affecting values overall

df_titanic.groupby(['Sex','Pclass'])['Fare'].describe()

               count       mean        std     min        25%       50%  \
Sex    Pclass
female 1        97.0  82.304167  66.398922  6.4375  28.712500  71.00000
       2        45.0  30.225558  46.715697  4.0125   8.050000  13.00000
       3        46.0  30.636326  42.321437  4.0125   9.283350  13.68125
       ?        38.0  56.819079  58.759846  7.1250   9.838550  31.84790
male   1       121.0  63.890185  78.324924  0.0000  26.387500  39.00000
       2        45.0  38.248796  37.418986  5.0000  12.287500  23.45000
       3        36.0  50.323031  93.910767  7.5500   8.050000  15.39790
       ?        48.0  36.873269  41.366004  0.0000  12.297925  27.00415

                      75%       max
Sex    Pclass
female 1       110.883300  263.0000
       2        27.900000  221.7792
       3        34.987500  262.3750
       ?        85.339575  227.5250
male   1        78.850000  512.3292
       2        56.929200  135.6333
       3        49.625000  512.3292
       ?        46.950000  247.5208

In [24]:
#https://github.com/learn-co-curriculum/dsc-pivot-tables-pandas

In [23]:
#PIVOT TABLES
#uses dataframe.pivot()
#takes 3 parameters:
# 1 index - column that u want to use as new index #1
# 2 column - columns to be used as new columns - this is what you convert to wide format
# values -  what data we expect to be looking at

#EG some_dataframe.pivot(index='State', columns='Gender', values='Deaths_mean')

# it is key to pivot with a categorical column rather than a continous/ numerical column

In [26]:
df_titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
6,7.0,0.0,1,"McCarthy, Mr. Timothy J",male,54.0,0.0,0.0,17463,51.8625,E46,S

In [31]:
df_titanic.pivot(columns='Sex', values=['Age', 'Fare']).describe()

              Age                    Fare
Sex        female        male      female        male
count  226.000000  250.000000  226.000000  250.000000
mean    30.959867   34.748680   57.132966   52.133817
std     17.830544   19.261448   61.606565   70.099645
min      0.420000    0.420000    4.012500    0.000000
25%     18.000000   20.625000   10.500000   12.875000
50%     30.750000   35.000000   29.850000   30.035400
75%     44.000000   48.000000   79.450000   65.789575
max     74.000000   80.000000  263.000000  512.329200

In [38]:
#pivot table to count number of passangers per class
df_titanic.pivot_table(columns='Pclass', index='Survived', values='Name', aggfunc='count')

Pclass      1   2   3   ?
Survived
0.0        87  46  39  46
1.0       131  44  43  40

In [41]:
# pivot table for average age of each survival group
#pivot table of survived
df_titanic.pivot_table(columns ='Survived', values='Age', aggfunc='mean')

Survived       0.0        1.0
Age       33.97445  32.083992

In [42]:
# PIVOT TABLES WITH AGGREGATE FUNCTIONS
# - involves just asking for multiple functions eg sum,count etc
# use .agg(mean......)

In [48]:
df_titanic.pivot(columns ='Survived', values='Age',).agg(['mean','min','max','count'])

Survived        0.0         1.0
mean       33.97445   32.083992
min         0.42000    0.420000
max        74.00000   80.000000
count     218.00000  258.000000

In [49]:
# PIVOT MULTIPLE COLUMNS

In [57]:
df_titanic.pivot( columns=['Sex','Pclass'], values=['Age','Fare']).describe()

              Age                                                          \
Sex        female        male     female       male     female       male
Pclass          1           1          3          2          2          3
count   97.000000  121.000000  46.000000  45.000000  45.000000  36.000000
mean    33.278351   37.213554  32.400435  31.318444  25.540889  31.493056
std     16.287572   18.409346  20.114176  19.197784  17.297712  19.001025
min      0.750000    0.420000   0.670000   0.830000   0.920000   0.420000
25%     21.000000   25.000000  18.000000  15.000000  12.000000  18.000000
50%     33.000000   37.000000  33.500000  34.000000  24.000000  29.750000
75%     47.000000   49.000000  48.500000  45.000000  36.000000  42.000000
max     74.000000   80.000000  70.000000  74.000000  65.000000  71.000000

                                    Fare                                      \
Sex                   female      female        male      female        male
Pclass          ?          ?           1           1           3           2
count   48.000000  38.000000   97.000000  121.000000   46.000000   45.000000
mean    34.192708  29.715000   82.304167   63.890185   30.636326   38.248796
std     21.237026  18.525312   66.398922   78.324924   42.321437   37.418986
min      0.750000   0.420000    6.437500    0.000000    4.012500    5.000000
25%     14.875000  18.000000   28.712500   26.387500    9.283350   12.287500
50%     33.000000  30.750000   71.000000   39.000000   13.681250   23.450000
75%     49.250000  36.000000  110.883300   78.850000   34.987500   56.929200
max     80.000000  74.000000  263.000000  512.329200  262.375000  135.633300


Sex         female        male                  female
Pclass           2           3           ?           ?
count    45.000000   36.000000   48.000000   38.000000
mean     30.225558   50.323031   36.873269   56.819079
std      46.715697   93.910767   41.366004   58.759846
min       4.012500    7.550000    0.000000    7.125000
25%       8.050000    8.050000   12.297925    9.838550
50%      13.000000   15.397900   27.004150   31.847900
75%      27.900000   49.625000   46.950000   85.339575
max     221.779200  512.329200  247.520800  227.525000